// lib/a1/emoji-keywords.ts
//
// СГЕНЕРИРОВАННЫЙ ФАЙЛ. Не правьте руками -- перегенерируйте.
//
// Александр, 17.09.2026: «Поиск в панели эмодзи ищет по названиям
// категорий, а не по эмодзи». Так и было: искать было не по чему --
// у набора в lib/a1/emoji-data.ts нет ни одного слова на эмодзи.
//
// Тянуть emoji-mart ради этого не хотелось (реальная новая
// зависимость), а слова уже лежат в самом Юникоде: у каждого символа
// есть официальное имя ("DOG FACE", "FIRE", "RED HEART"). Файл собран
// из них скриптом (unicodedata.name по каждому codepoint, служебные
// слова выброшены), поэтому поиск работает по-английски: "dog",
// "heart", "fire", "car".
//
// Русские и украинские слова переводятся в эти же английские через
// EMOJI_QUERY_ALIASES в lib/a1/emoji-search.ts -- список там короткий и
// ведётся руками, дополняйте по мере жалоб.
//
// Перегенерировать:
//   python3 scripts/gen-emoji-keywords.py

/** Эмодзи -> английские слова из имён Юникода, через пробел. */
export const EMOJI_KEYWORDS: Record<string, string> = {
  "😀": "grinning face",
  "😃": "smiling face open mouth",
  "😄": "smiling face open mouth eyes",
  "😁": "grinning face smiling eyes",
  "😆": "smiling face open mouth tightly closed eyes",
  "😅": "smiling face open mouth cold sweat",
  "🤣": "rolling on floor laughing",
  "😂": "face tears joy",
  "🙂": "slightly smiling face",
  "🙃": "upside down face",
  "😉": "winking face",
  "😊": "smiling face eyes",
  "😇": "smiling face halo",
  "🥰": "smiling face eyes three hearts",
  "😍": "smiling face heart shaped eyes",
  "🤩": "grinning face star eyes",
  "😘": "face throwing a kiss",
  "😗": "kissing face",
  "😚": "kissing face closed eyes",
  "😙": "kissing face smiling eyes",
  "😋": "face savouring delicious food",
  "😛": "face stuck out tongue",
  "😜": "face stuck out tongue winking eye",
  "🤪": "grinning face one large small eye",
  "😝": "face stuck out tongue tightly closed eyes",
  "🤑": "money mouth face",
  "🤗": "hugging face",
  "🤭": "smiling face eyes hand covering mouth",
  "🤫": "face finger covering closed lips",
  "🤔": "thinking face",
  "🤐": "zipper mouth face",
  "🤨": "face one eyebrow raised",
  "😐": "neutral face",
  "😑": "expressionless face",
  "😶": "face without mouth",
  "😏": "smirking face",
  "😒": "unamused face",
  "🙄": "face rolling eyes",
  "😬": "grimacing face",
  "🤥": "lying face",
  "😌": "relieved face",
  "😔": "pensive face",
  "😪": "sleepy face",
  "🤤": "drooling face",
  "😴": "sleeping face",
  "😷": "face medical mask",
  "🤒": "face thermometer",
  "🤕": "face head bandage",
  "🤢": "nauseated face",
  "🤮": "face open mouth vomiting",
  "🤧": "sneezing face",
  "🥵": "overheated face",
  "🥶": "freezing face",
  "🥴": "face uneven eyes wavy mouth",
  "😵": "dizzy face",
  "🤯": "shocked face exploding head",
  "🤠": "face cowboy hat",
  "🥳": "face party horn hat",
  "😎": "smiling face sunglasses",
  "🤓": "nerd face",
  "🧐": "face monocle",
  "😕": "confused face",
  "😟": "worried face",
  "🙁": "slightly frowning face",
  "☹️": "white frowning face",
  "😮": "face open mouth",
  "😯": "hushed face",
  "😲": "astonished face",
  "😳": "flushed face",
  "🥺": "face pleading eyes",
  "😦": "frowning face open mouth",
  "😧": "anguished face",
  "😨": "fearful face",
  "😰": "face open mouth cold sweat",
  "😥": "disappointed but relieved face",
  "😢": "crying face",
  "😭": "loudly crying face",
  "😱": "face screaming in fear",
  "😖": "confounded face",
  "😣": "persevering face",
  "😞": "disappointed face",
  "😓": "face cold sweat",
  "😩": "weary face",
  "😫": "tired face",
  "🥱": "yawning face",
  "😤": "face look triumph",
  "😡": "pouting face",
  "😠": "angry face",
  "🤬": "serious face symbols covering mouth",
  "😈": "smiling face horns",
  "👿": "imp",
  "💀": "skull",
  "😺": "smiling cat face open mouth",
  "😸": "grinning cat face smiling eyes",
  "😹": "cat face tears joy",
  "😻": "smiling cat face heart shaped eyes",
  "🥲": "smiling face tear",
  "👋": "waving hand",
  "🤚": "raised back hand",
  "🖐️": "raised hand fingers splayed",
  "✋": "raised hand",
  "🖖": "raised hand part between middle ring fingers",
  "👌": "ok hand",
  "🤌": "pinched fingers",
  "🤏": "pinching hand",
  "✌️": "victory hand",
  "🤞": "hand index middle fingers crossed",
  "🤟": "i love you hand",
  "🤘": "horns",
  "🤙": "call me hand",
  "👈": "white left pointing backhand index",
  "👉": "white right pointing backhand index",
  "👆": "white up pointing backhand index",
  "🖕": "reversed hand middle finger extended",
  "👇": "white down pointing backhand index",
  "☝️": "white up pointing index",
  "👍": "thumbs up",
  "👎": "thumbs down",
  "✊": "raised fist",
  "👊": "fisted hand",
  "🤛": "left facing fist",
  "🤜": "right facing fist",
  "👏": "clapping hands",
  "🙌": "person raising both hands in celebration",
  "👐": "open hands",
  "🤲": "palms up together",
  "🙏": "person folded hands",
  "✍️": "writing hand",
  "💅": "nail polish",
  "🤳": "selfie",
  "💪": "flexed biceps",
  "🦾": "mechanical arm",
  "🦿": "mechanical leg",
  "🦵": "leg",
  "🦶": "foot",
  "👂": "ear",
  "🦻": "ear hearing aid",
  "👃": "nose",
  "🧠": "brain",
  "🦷": "tooth",
  "🦴": "bone",
  "👀": "eyes",
  "👁️": "eye",
  "👅": "tongue",
  "👄": "mouth",
  "🤝": "handshake",
  "👶": "baby",
  "🧒": "child",
  "👦": "boy",
  "👧": "girl",
  "🧑": "adult",
  "👱": "person blond hair",
  "👨": "man",
  "🧔": "bearded person",
  "👩": "woman",
  "🧓": "older adult",
  "👴": "older man",
  "👵": "older woman",
  "🙍": "person frowning",
  "🙎": "person pouting face",
  "🙅": "face no good gesture",
  "🙆": "face ok gesture",
  "💁": "information desk person",
  "🙋": "happy person raising one hand",
  "🧏": "deaf person",
  "🙇": "person bowing deeply",
  "🤦": "face palm",
  "🤷": "shrug",
  "👮": "police officer",
  "🕵️": "sleuth or spy",
  "💂": "guardsman",
  "🥷": "ninja",
  "👷": "construction worker",
  "🤴": "prince",
  "👸": "princess",
  "👳": "man turban",
  "👲": "man gua pi mao",
  "🧕": "person headscarf",
  "🤵": "man in tuxedo",
  "👰": "bride veil",
  "🤰": "pregnant woman",
  "🤱": "breast feeding",
  "👼": "baby angel",
  "🎅": "father christmas",
  "🤶": "mother christmas",
  "🦸": "superhero",
  "🦹": "supervillain",
  "🧙": "mage",
  "🧚": "fairy",
  "🧛": "vampire",
  "🧜": "merperson",
  "🧝": "elf",
  "🧞": "genie",
  "🧟": "zombie",
  "🐶": "dog face",
  "🐱": "cat face",
  "🐭": "mouse face",
  "🐹": "hamster face",
  "🐰": "rabbit face",
  "🦊": "fox face",
  "🐻": "bear face",
  "🐼": "panda face",
  "🐻‍❄️": "bear face snowflake",
  "🐨": "koala",
  "🐯": "tiger face",
  "🦁": "lion face",
  "🐮": "cow face",
  "🐷": "pig face",
  "🐽": "pig nose",
  "🐸": "frog face",
  "🐵": "monkey face",
  "🙈": "see no evil monkey",
  "🙉": "hear no evil monkey",
  "🙊": "speak no evil monkey",
  "🐒": "monkey",
  "🐔": "chicken",
  "🐧": "penguin",
  "🐦": "bird",
  "🐤": "baby chick",
  "🐣": "hatching chick",
  "🐥": "front facing baby chick",
  "🦆": "duck",
  "🦅": "eagle",
  "🦉": "owl",
  "🦇": "bat",
  "🐺": "wolf face",
  "🐗": "boar",
  "🐴": "horse face",
  "🦄": "unicorn face",
  "🐝": "honeybee",
  "🐛": "bug",
  "🦋": "butterfly",
  "🐌": "snail",
  "🐞": "lady beetle",
  "🐜": "ant",
  "🪲": "beetle",
  "🪳": "cockroach",
  "🦟": "mosquito",
  "🦗": "cricket",
  "🕷️": "spider",
  "🕸️": "spider web",
  "🦂": "scorpion",
  "🐢": "turtle",
  "🐍": "snake",
  "🦎": "lizard",
  "🦖": "t rex",
  "🦕": "sauropod",
  "🐙": "octopus",
  "🦑": "squid",
  "🦐": "shrimp",
  "🦞": "lobster",
  "🦀": "crab",
  "🐡": "blowfish",
  "🐠": "tropical fish",
  "🐟": "fish",
  "🐬": "dolphin",
  "🐳": "spouting whale",
  "🐋": "whale",
  "🦈": "shark",
  "🐊": "crocodile",
  "🐅": "tiger",
  "🐆": "leopard",
  "🦓": "zebra face",
  "🦍": "gorilla",
  "🦧": "orangutan",
  "🐘": "elephant",
  "🦣": "mammoth",
  "🦏": "rhinoceros",
  "🦛": "hippopotamus",
  "🐪": "dromedary camel",
  "🐫": "bactrian camel",
  "🦒": "giraffe face",
  "🦘": "kangaroo",
  "🐃": "water buffalo",
  "🍀": "four leaf clover",
  "🍏": "green apple",
  "🍎": "red apple",
  "🍐": "pear",
  "🍊": "tangerine",
  "🍋": "lemon",
  "🍌": "banana",
  "🍉": "watermelon",
  "🍇": "grapes",
  "🍓": "strawberry",
  "🫐": "blueberries",
  "🍈": "melon",
  "🍒": "cherries",
  "🍑": "peach",
  "🥭": "mango",
  "🍍": "pineapple",
  "🥥": "coconut",
  "🥝": "kiwifruit",
  "🍅": "tomato",
  "🍆": "aubergine",
  "🥑": "avocado",
  "🥦": "broccoli",
  "🥬": "leafy green",
  "🥒": "cucumber",
  "🌶️": "hot pepper",
  "🫑": "bell pepper",
  "🌽": "ear maize",
  "🥕": "carrot",
  "🫒": "olive",
  "🧄": "garlic",
  "🧅": "onion",
  "🥔": "potato",
  "🍠": "roasted sweet potato",
  "🥐": "croissant",
  "🥯": "bagel",
  "🍞": "bread",
  "🥖": "baguette bread",
  "🥨": "pretzel",
  "🧀": "cheese wedge",
  "🥚": "egg",
  "🍳": "cooking",
  "🧈": "butter",
  "🥞": "pancakes",
  "🧇": "waffle",
  "🥓": "bacon",
  "🥩": "cut meat",
  "🍗": "poultry leg",
  "🍖": "meat on bone",
  "🌭": "hot dog",
  "🍔": "hamburger",
  "🍟": "french fries",
  "🍕": "slice pizza",
  "🫓": "flatbread",
  "🥪": "sandwich",
  "🥙": "stuffed flatbread",
  "🧆": "falafel",
  "🌮": "taco",
  "🌯": "burrito",
  "🫔": "tamale",
  "🥗": "green salad",
  "🥘": "shallow pan food",
  "🫕": "fondue",
  "🍝": "spaghetti",
  "🍜": "steaming bowl",
  "🍲": "pot food",
  "🍛": "curry rice",
  "🍣": "sushi",
  "🍱": "bento box",
  "🥟": "dumpling",
  "🦪": "oyster",
  "🍤": "fried shrimp",
  "🍙": "rice ball",
  "🍚": "cooked rice",
  "🍘": "rice cracker",
  "🍥": "fish cake swirl design",
  "🥠": "fortune cookie",
  "🥮": "moon cake",
  "🍢": "oden",
  "🍡": "dango",
  "🍧": "shaved ice",
  "🍨": "ice cream",
  "🍦": "soft ice cream",
  "🥧": "pie",
  "🧁": "cupcake",
  "🍰": "shortcake",
  "🎂": "birthday cake",
  "🍮": "custard",
  "🍭": "lollipop",
  "🍬": "candy",
  "🍫": "chocolate bar",
  "🍿": "popcorn",
  "🍩": "doughnut",
  "🍪": "cookie",
  "☕": "hot beverage",
  "🍵": "teacup without handle",
  "🧃": "beverage box",
  "🥤": "cup straw",
  "🍺": "beer mug",
  "🍻": "clinking beer mugs",
  "🥂": "clinking glasses",
  "🍷": "wine glass",
  "🥃": "tumbler glass",
  "🍸": "cocktail glass",
  "🍹": "tropical drink",
  "🧋": "bubble tea",
  "🍾": "bottle popping cork",
  "🥛": "glass milk",
  "⚽": "soccer ball",
  "🏀": "basketball hoop",
  "🏈": "american football",
  "⚾": "baseball",
  "🥎": "softball",
  "🎾": "tennis racquet ball",
  "🏐": "volleyball",
  "🏉": "rugby football",
  "🥏": "flying disc",
  "🎱": "billiards",
  "🪀": "yo",
  "🏓": "table tennis paddle ball",
  "🏸": "badminton racquet shuttlecock",
  "🏒": "ice hockey stick puck",
  "🏑": "field hockey stick ball",
  "🥍": "lacrosse stick ball",
  "🏏": "cricket bat ball",
  "🪃": "boomerang",
  "🥅": "goal net",
  "⛳": "flag in hole",
  "🪁": "kite",
  "🏹": "bow arrow",
  "🎣": "fishing pole fish",
  "🤿": "diving mask",
  "🥊": "boxing glove",
  "🥋": "martial arts uniform",
  "🎽": "running shirt sash",
  "🛹": "skateboard",
  "🛼": "roller skate",
  "🛷": "sled",
  "⛸️": "ice skate",
  "🥌": "curling stone",
  "🎿": "ski boot",
  "⛷️": "skier",
  "🏂": "snowboarder",
  "🪂": "parachute",
  "🏋️": "weight lifter",
  "🤼": "wrestlers",
  "🤸": "person doing cartwheel",
  "⛹️": "person ball",
  "🤺": "fencer",
  "🤾": "handball",
  "🏌️": "golfer",
  "🏇": "horse racing",
  "🧘": "person in lotus position",
  "🏄": "surfer",
  "🏊": "swimmer",
  "🤽": "water polo",
  "🚣": "rowboat",
  "🧗": "person climbing",
  "🚴": "bicyclist",
  "🚵": "mountain bicyclist",
  "🎪": "circus tent",
  "🎭": "performing arts",
  "🎨": "artist palette",
  "🎬": "clapper board",
  "🎤": "microphone",
  "🎧": "headphone",
  "🎼": "musical score",
  "🎹": "musical keyboard",
  "🥁": "drum drumsticks",
  "🎷": "saxophone",
  "🎺": "trumpet",
  "🎸": "guitar",
  "🪕": "banjo",
  "🎻": "violin",
  "🎲": "game die",
  "♟️": "black chess pawn",
  "🎯": "direct hit",
  "🎳": "bowling",
  "🎮": "video game",
  "🎰": "slot machine",
  "🎉": "party popper",
  "🎊": "confetti ball",
  "🏆": "trophy",
  "🥇": "first place medal",
  "🎁": "wrapped present",
  "🎈": "balloon",
  "🚗": "automobile",
  "🚕": "taxi",
  "🚙": "recreational vehicle",
  "🚌": "bus",
  "🚎": "trolleybus",
  "🏎️": "racing car",
  "🚓": "police car",
  "🚑": "ambulance",
  "🚒": "fire engine",
  "🚐": "minibus",
  "🛻": "pickup truck",
  "🚚": "delivery truck",
  "🚛": "articulated lorry",
  "🚜": "tractor",
  "🦯": "probing cane",
  "🦽": "manual wheelchair",
  "🦼": "motorized wheelchair",
  "🛴": "scooter",
  "🚲": "bicycle",
  "🛵": "motor scooter",
  "🏍️": "racing motorcycle",
  "🛺": "auto rickshaw",
  "🚨": "police cars revolving light",
  "🚔": "oncoming police car",
  "🚍": "oncoming bus",
  "🚘": "oncoming automobile",
  "🚖": "oncoming taxi",
  "🚡": "aerial tramway",
  "🚠": "mountain cableway",
  "🚟": "suspension railway",
  "🚃": "railway car",
  "🚋": "tram car",
  "🚞": "mountain railway",
  "🚝": "monorail",
  "🚄": "high speed train",
  "🚅": "high speed train bullet nose",
  "🚈": "light rail",
  "🚂": "steam locomotive",
  "🚆": "train",
  "🚇": "metro",
  "🚊": "tram",
  "🚉": "station",
  "✈️": "airplane",
  "🛫": "airplane departure",
  "🛬": "airplane arriving",
  "🛩️": "small airplane",
  "💺": "seat",
  "🛰️": "satellite",
  "🚀": "rocket",
  "🛸": "flying saucer",
  "🚁": "helicopter",
  "🛶": "canoe",
  "⛵": "sailboat",
  "🚤": "speedboat",
  "🛥️": "motor boat",
  "🛳️": "passenger ship",
  "⛴️": "ferry",
  "🚢": "ship",
  "⚓": "anchor",
  "⛽": "fuel pump",
  "🚧": "construction",
  "🚦": "vertical traffic light",
  "🚥": "horizontal traffic light",
  "🗺️": "world map",
  "🗿": "moyai",
  "🗽": "statue liberty",
  "🗼": "tokyo tower",
  "🏰": "european castle",
  "🏯": "japanese castle",
  "🏟️": "stadium",
  "🎡": "ferris wheel",
  "🎢": "roller coaster",
  "🎠": "carousel horse",
  "⛲": "fountain",
  "⛱️": "umbrella on ground",
  "🏖️": "beach umbrella",
  "🏝️": "desert island",
  "🏜️": "desert",
  "🌋": "volcano",
  "⛰️": "mountain",
  "🏔️": "snow capped mountain",
  "🗻": "mount fuji",
  "🏕️": "camping",
  "⛺": "tent",
  "🏠": "house building",
  "🏡": "house garden",
  "🏘️": "house buildings",
  "🏚️": "derelict house building",
  "🏗️": "building construction",
  "🏭": "factory",
  "🏢": "office building",
  "🏬": "department store",
  "🏣": "japanese post office",
  "🏤": "european post office",
  "🏥": "hospital",
  "🏦": "bank",
  "🔥": "fire",
  "⚡": "high voltage",
  "⭐": "white medium star",
  "🌟": "glowing star",
  "💥": "collision",
  "⌚": "watch",
  "📱": "mobile phone",
  "💻": "personal computer",
  "⌨️": "keyboard",
  "🖥️": "desktop computer",
  "🖨️": "printer",
  "🖱️": "three button mouse",
  "🖲️": "trackball",
  "💽": "minidisc",
  "💾": "floppy disk",
  "💿": "optical disc",
  "📀": "dvd",
  "📷": "camera",
  "📸": "camera flash",
  "📹": "video camera",
  "🎥": "movie camera",
  "📞": "telephone receiver",
  "☎️": "black telephone",
  "📟": "pager",
  "📠": "fax machine",
  "📺": "television",
  "📻": "radio",
  "🎙️": "studio microphone",
  "🎚️": "level slider",
  "🎛️": "control knobs",
  "⏱️": "stopwatch",
  "⏲️": "timer clock",
  "⏰": "alarm clock",
  "🕰️": "mantelpiece clock",
  "⌛": "hourglass",
  "⏳": "hourglass flowing sand",
  "📡": "satellite antenna",
  "🔋": "battery",
  "🔌": "electric plug",
  "💡": "electric light bulb",
  "🔦": "electric torch",
  "🕯️": "candle",
  "🪔": "diya lamp",
  "🧯": "fire extinguisher",
  "🛢️": "oil drum",
  "💸": "money wings",
  "💵": "banknote dollar",
  "💴": "banknote yen",
  "💶": "banknote euro",
  "💷": "banknote pound",
  "🪙": "coin",
  "💰": "money bag",
  "💳": "credit card",
  "🧾": "receipt",
  "💎": "gem stone",
  "⚖️": "scales",
  "🪜": "ladder",
  "🧰": "toolbox",
  "🪛": "screwdriver",
  "🔧": "wrench",
  "🔨": "hammer",
  "⚒️": "hammer pick",
  "🛠️": "hammer wrench",
  "⛏️": "pick",
  "🪚": "carpentry saw",
  "🔩": "nut bolt",
  "⚙️": "gear",
  "🪤": "mouse trap",
  "🧱": "brick",
  "⛓️": "chains",
  "🧲": "magnet",
  "🔫": "pistol",
  "💣": "bomb",
  "🧨": "firecracker",
  "🪓": "axe",
  "🔪": "hocho",
  "🗡️": "dagger knife",
  "⚔️": "crossed swords",
  "🛡️": "shield",
  "🚬": "smoking",
  "⚰️": "coffin",
  "🪦": "headstone",
  "⚱️": "funeral urn",
  "🏺": "amphora",
  "🔮": "crystal ball",
  "💼": "briefcase",
  "📌": "pushpin",
  "📎": "paperclip",
  "🔗": "link",
  "💬": "speech balloon",
  "🕐": "clock face one oclock",
  "📈": "chart upwards trend",
  "📉": "chart downwards trend",
  "🔑": "key",
  "❤️": "heavy black heart",
  "🧡": "orange heart",
  "💛": "yellow heart",
  "💚": "green heart",
  "💙": "blue heart",
  "💜": "purple heart",
  "🖤": "black heart",
  "🤍": "white heart",
  "🤎": "brown heart",
  "💔": "broken heart",
  "❤️‍🔥": "heavy black heart fire",
  "❤️‍🩹": "heavy black heart adhesive bandage",
  "💕": "two hearts",
  "💞": "revolving hearts",
  "💓": "beating heart",
  "💗": "growing heart",
  "💖": "sparkling heart",
  "💘": "heart arrow",
  "💝": "heart ribbon",
  "💟": "heart decoration",
  "☮️": "peace",
  "✝️": "latin cross",
  "☪️": "star crescent",
  "🕉️": "om",
  "☸️": "wheel dharma",
  "✡️": "star david",
  "🔯": "six pointed star middle dot",
  "🕎": "menorah nine branches",
  "☯️": "yin yang",
  "☦️": "orthodox cross",
  "🛐": "place worship",
  "⛎": "ophiuchus",
  "♈": "aries",
  "♉": "taurus",
  "♊": "gemini",
  "♋": "cancer",
  "♌": "leo",
  "♍": "virgo",
  "♎": "libra",
  "♏": "scorpius",
  "♐": "sagittarius",
  "♑": "capricorn",
  "♒": "aquarius",
  "♓": "pisces",
  "🆔": "squared id",
  "⚛️": "atom",
  "🉑": "circled ideograph accept",
  "☢️": "radioactive",
  "☣️": "biohazard",
  "📴": "mobile phone off",
  "📳": "vibration mode",
  "🈶": "squared cjk unified ideograph 6709",
  "🈚": "squared cjk unified ideograph 7121",
  "🈸": "squared cjk unified ideograph 7533",
  "🈺": "squared cjk unified ideograph 55b6",
  "🈷️": "squared cjk unified ideograph 6708",
  "✴️": "eight pointed black star",
  "🆚": "squared vs",
  "💮": "white flower",
  "🉐": "circled ideograph advantage",
  "㊙️": "circled ideograph secret",
  "㊗️": "circled ideograph congratulation",
  "🈴": "squared cjk unified ideograph 5408",
  "🈵": "squared cjk unified ideograph 6e80",
  "🔴": "large red circle",
  "🟠": "large orange circle",
  "🟡": "large yellow circle",
  "🟢": "large green circle",
  "🔵": "large blue circle",
  "🟣": "large purple circle",
  "🟤": "large brown circle",
  "⚫": "medium black circle",
  "⚪": "medium white circle",
  "🟥": "large red square",
  "🟧": "large orange square",
  "🟨": "large yellow square",
  "🟩": "large green square",
  "🟦": "large blue square",
  "🟪": "large purple square",
  "🟫": "large brown square",
  "⬛": "black large square",
  "⬜": "white large square",
  "◼️": "black medium square",
  "◻️": "white medium square",
  "◾": "black medium small square",
  "◽": "white medium small square",
  "▪️": "black small square",
  "▫️": "white small square",
  "🔶": "large orange diamond",
  "🔷": "large blue diamond",
  "🔸": "small orange diamond",
  "🔹": "small blue diamond",
  "🔺": "up pointing red triangle",
  "🔻": "down pointing red triangle",
  "💠": "diamond shape a dot inside",
  "🔘": "radio button",
  "✅": "white heavy check mark",
  "❌": "cross mark",
  "❎": "negative squared cross mark",
  "➕": "heavy plus",
  "➖": "heavy minus",
  "➗": "heavy division",
  "♾️": "permanent paper",
  "💯": "hundred points",
  "🔞": "no one under eighteen",
  "📵": "no mobile phones",
  "🚫": "no entry",
  "❗": "heavy exclamation mark",
  "❓": "black question mark ornament",
  "‼️": "double exclamation mark",
  "⁉️": "exclamation question mark",
  "💤": "sleeping",
  "♥️": "black heart suit",
};
