// lib/seo/country-names.ts
//
// 01.10.2026 (Александр: «нужна локализация на все страны из списка»).
// Названия стран для de / es / fr / pl / pt-BR / zh (uk, ru и en живут в
// countries.ts). Сгенерировано из CLDR (Intl.DisplayNames) и ЗАПЕЧЕНО в код,
// а не считается в браузере: у сервера и у iOS-Safari версии CLDR разные, и
// одно и то же название могло бы отличаться -- это ошибка гидратации.

import type { Locale } from "@/components/t";

type Extra = Partial<Record<Locale, string>>;

export const COUNTRY_NAMES: Record<string, Extra> = {
  AR: { de: "Argentinien", es: "Argentina", fr: "Argentine", pl: "Argentyna", ptBR: "Argentina", zh: "阿根廷" },
  AM: { de: "Armenien", es: "Armenia", fr: "Arménie", pl: "Armenia", ptBR: "Armênia", zh: "亚美尼亚" },
  AU: { de: "Australien", es: "Australia", fr: "Australie", pl: "Australia", ptBR: "Austrália", zh: "澳大利亚" },
  AT: { de: "Österreich", es: "Austria", fr: "Autriche", pl: "Austria", ptBR: "Áustria", zh: "奥地利" },
  AZ: { de: "Aserbaidschan", es: "Azerbaiyán", fr: "Azerbaïdjan", pl: "Azerbejdżan", ptBR: "Azerbaijão", zh: "阿塞拜疆" },
  BD: { de: "Bangladesch", es: "Bangladés", fr: "Bangladesh", pl: "Bangladesz", ptBR: "Bangladesh", zh: "孟加拉国" },
  BY: { de: "Belarus", es: "Bielorrusia", fr: "Biélorussie", pl: "Białoruś", ptBR: "Bielorrússia", zh: "白俄罗斯" },
  BE: { de: "Belgien", es: "Bélgica", fr: "Belgique", pl: "Belgia", ptBR: "Bélgica", zh: "比利时" },
  BR: { de: "Brasilien", es: "Brasil", fr: "Brésil", pl: "Brazylia", ptBR: "Brasil", zh: "巴西" },
  BG: { de: "Bulgarien", es: "Bulgaria", fr: "Bulgarie", pl: "Bułgaria", ptBR: "Bulgária", zh: "保加利亚" },
  CA: { de: "Kanada", es: "Canadá", fr: "Canada", pl: "Kanada", ptBR: "Canadá", zh: "加拿大" },
  CL: { de: "Chile", es: "Chile", fr: "Chili", pl: "Chile", ptBR: "Chile", zh: "智利" },
  CN: { de: "China", es: "China", fr: "Chine", pl: "Chiny", ptBR: "China", zh: "中国" },
  CO: { de: "Kolumbien", es: "Colombia", fr: "Colombie", pl: "Kolumbia", ptBR: "Colômbia", zh: "哥伦比亚" },
  HR: { de: "Kroatien", es: "Croacia", fr: "Croatie", pl: "Chorwacja", ptBR: "Croácia", zh: "克罗地亚" },
  CY: { de: "Zypern", es: "Chipre", fr: "Chypre", pl: "Cypr", ptBR: "Chipre", zh: "塞浦路斯" },
  CZ: { de: "Tschechien", es: "Chequia", fr: "Tchéquie", pl: "Czechy", ptBR: "Tchéquia", zh: "捷克" },
  DK: { de: "Dänemark", es: "Dinamarca", fr: "Danemark", pl: "Dania", ptBR: "Dinamarca", zh: "丹麦" },
  EG: { de: "Ägypten", es: "Egipto", fr: "Égypte", pl: "Egipt", ptBR: "Egito", zh: "埃及" },
  EE: { de: "Estland", es: "Estonia", fr: "Estonie", pl: "Estonia", ptBR: "Estônia", zh: "爱沙尼亚" },
  FI: { de: "Finnland", es: "Finlandia", fr: "Finlande", pl: "Finlandia", ptBR: "Finlândia", zh: "芬兰" },
  FR: { de: "Frankreich", es: "Francia", fr: "France", pl: "Francja", ptBR: "França", zh: "法国" },
  GE: { de: "Georgien", es: "Georgia", fr: "Géorgie", pl: "Gruzja", ptBR: "Geórgia", zh: "格鲁吉亚" },
  DE: { de: "Deutschland", es: "Alemania", fr: "Allemagne", pl: "Niemcy", ptBR: "Alemanha", zh: "德国" },
  GR: { de: "Griechenland", es: "Grecia", fr: "Grèce", pl: "Grecja", ptBR: "Grécia", zh: "希腊" },
  HU: { de: "Ungarn", es: "Hungría", fr: "Hongrie", pl: "Węgry", ptBR: "Hungria", zh: "匈牙利" },
  IS: { de: "Island", es: "Islandia", fr: "Islande", pl: "Islandia", ptBR: "Islândia", zh: "冰岛" },
  IN: { de: "Indien", es: "India", fr: "Inde", pl: "Indie", ptBR: "Índia", zh: "印度" },
  ID: { de: "Indonesien", es: "Indonesia", fr: "Indonésie", pl: "Indonezja", ptBR: "Indonésia", zh: "印度尼西亚" },
  IE: { de: "Irland", es: "Irlanda", fr: "Irlande", pl: "Irlandia", ptBR: "Irlanda", zh: "爱尔兰" },
  IL: { de: "Israel", es: "Israel", fr: "Israël", pl: "Izrael", ptBR: "Israel", zh: "以色列" },
  IT: { de: "Italien", es: "Italia", fr: "Italie", pl: "Włochy", ptBR: "Itália", zh: "意大利" },
  JP: { de: "Japan", es: "Japón", fr: "Japon", pl: "Japonia", ptBR: "Japão", zh: "日本" },
  KZ: { de: "Kasachstan", es: "Kazajistán", fr: "Kazakhstan", pl: "Kazachstan", ptBR: "Cazaquistão", zh: "哈萨克斯坦" },
  KE: { de: "Kenia", es: "Kenia", fr: "Kenya", pl: "Kenia", ptBR: "Quênia", zh: "肯尼亚" },
  KR: { de: "Südkorea", es: "Corea del Sur", fr: "Corée du Sud", pl: "Korea Południowa", ptBR: "Coreia do Sul", zh: "韩国" },
  LV: { de: "Lettland", es: "Letonia", fr: "Lettonie", pl: "Łotwa", ptBR: "Letônia", zh: "拉脱维亚" },
  LT: { de: "Litauen", es: "Lituania", fr: "Lituanie", pl: "Litwa", ptBR: "Lituânia", zh: "立陶宛" },
  MY: { de: "Malaysia", es: "Malasia", fr: "Malaisie", pl: "Malezja", ptBR: "Malásia", zh: "马来西亚" },
  MD: { de: "Republik Moldau", es: "Moldavia", fr: "Moldavie", pl: "Mołdawia", ptBR: "Moldávia", zh: "摩尔多瓦" },
  NP: { de: "Nepal", es: "Nepal", fr: "Népal", pl: "Nepal", ptBR: "Nepal", zh: "尼泊尔" },
  NL: { de: "Niederlande", es: "Países Bajos", fr: "Pays-Bas", pl: "Holandia", ptBR: "Países Baixos", zh: "荷兰" },
  NZ: { de: "Neuseeland", es: "Nueva Zelanda", fr: "Nouvelle-Zélande", pl: "Nowa Zelandia", ptBR: "Nova Zelândia", zh: "新西兰" },
  NG: { de: "Nigeria", es: "Nigeria", fr: "Nigeria", pl: "Nigeria", ptBR: "Nigéria", zh: "尼日利亚" },
  NO: { de: "Norwegen", es: "Noruega", fr: "Norvège", pl: "Norwegia", ptBR: "Noruega", zh: "挪威" },
  PK: { de: "Pakistan", es: "Pakistán", fr: "Pakistan", pl: "Pakistan", ptBR: "Paquistão", zh: "巴基斯坦" },
  PE: { de: "Peru", es: "Perú", fr: "Pérou", pl: "Peru", ptBR: "Peru", zh: "秘鲁" },
  PH: { de: "Philippinen", es: "Filipinas", fr: "Philippines", pl: "Filipiny", ptBR: "Filipinas", zh: "菲律宾" },
  PL: { de: "Polen", es: "Polonia", fr: "Pologne", pl: "Polska", ptBR: "Polônia", zh: "波兰" },
  PT: { de: "Portugal", es: "Portugal", fr: "Portugal", pl: "Portugalia", ptBR: "Portugal", zh: "葡萄牙" },
  QA: { de: "Katar", es: "Catar", fr: "Qatar", pl: "Katar", ptBR: "Catar", zh: "卡塔尔" },
  RO: { de: "Rumänien", es: "Rumanía", fr: "Roumanie", pl: "Rumunia", ptBR: "Romênia", zh: "罗马尼亚" },
  SA: { de: "Saudi-Arabien", es: "Arabia Saudí", fr: "Arabie saoudite", pl: "Arabia Saudyjska", ptBR: "Arábia Saudita", zh: "沙特阿拉伯" },
  RS: { de: "Serbien", es: "Serbia", fr: "Serbie", pl: "Serbia", ptBR: "Sérvia", zh: "塞尔维亚" },
  SK: { de: "Slowakei", es: "Eslovaquia", fr: "Slovaquie", pl: "Słowacja", ptBR: "Eslováquia", zh: "斯洛伐克" },
  SI: { de: "Slowenien", es: "Eslovenia", fr: "Slovénie", pl: "Słowenia", ptBR: "Eslovênia", zh: "斯洛文尼亚" },
  ZA: { de: "Südafrika", es: "Sudáfrica", fr: "Afrique du Sud", pl: "Republika Południowej Afryki", ptBR: "África do Sul", zh: "南非" },
  ES: { de: "Spanien", es: "España", fr: "Espagne", pl: "Hiszpania", ptBR: "Espanha", zh: "西班牙" },
  LK: { de: "Sri Lanka", es: "Sri Lanka", fr: "Sri Lanka", pl: "Sri Lanka", ptBR: "Sri Lanka", zh: "斯里兰卡" },
  SE: { de: "Schweden", es: "Suecia", fr: "Suède", pl: "Szwecja", ptBR: "Suécia", zh: "瑞典" },
  CH: { de: "Schweiz", es: "Suiza", fr: "Suisse", pl: "Szwajcaria", ptBR: "Suíça", zh: "瑞士" },
  TH: { de: "Thailand", es: "Tailandia", fr: "Thaïlande", pl: "Tajlandia", ptBR: "Tailândia", zh: "泰国" },
  TR: { de: "Türkei", es: "Turquía", fr: "Turquie", pl: "Turcja", ptBR: "Turquia", zh: "土耳其" },
  UA: { de: "Ukraine", es: "Ucrania", fr: "Ukraine", pl: "Ukraina", ptBR: "Ucrânia", zh: "乌克兰" },
  AE: { de: "Vereinigte Arabische Emirate", es: "Emiratos Árabes Unidos", fr: "Émirats arabes unis", pl: "Zjednoczone Emiraty Arabskie", ptBR: "Emirados Árabes Unidos", zh: "阿拉伯联合酋长国" },
  GB: { de: "Vereinigtes Königreich", es: "Reino Unido", fr: "Royaume-Uni", pl: "Wielka Brytania", ptBR: "Reino Unido", zh: "英国" },
  US: { de: "Vereinigte Staaten", es: "Estados Unidos", fr: "États-Unis", pl: "Stany Zjednoczone", ptBR: "Estados Unidos", zh: "美国" },
  UY: { de: "Uruguay", es: "Uruguay", fr: "Uruguay", pl: "Urugwaj", ptBR: "Uruguai", zh: "乌拉圭" },
  UZ: { de: "Usbekistan", es: "Uzbekistán", fr: "Ouzbékistan", pl: "Uzbekistan", ptBR: "Uzbequistão", zh: "乌兹别克斯坦" },
  VN: { de: "Vietnam", es: "Vietnam", fr: "Viêt Nam", pl: "Wietnam", ptBR: "Vietnã", zh: "越南" },
  WW: { de: "Weltweit", es: "En todo el mundo", fr: "Monde entier", pl: "Cały świat", ptBR: "Mundo todo", zh: "全球" },
};
